/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppNewDealRouteImport } from './routes/app.new-deal'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSuppliersIndexRouteImport } from './routes/app.suppliers.index'
import { Route as AppEscrowsIndexRouteImport } from './routes/app.escrows.index'
import { Route as AppSuppliersIdRouteImport } from './routes/app.suppliers.$id'
import { Route as AppEscrowsIdRouteImport } from './routes/app.escrows.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppNewDealRoute = AppNewDealRouteImport.update({
  id: '/new-deal',
  path: '/new-deal',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppEscrowsIndexRoute = AppEscrowsIndexRouteImport.update({
  id: '/escrows/',
  path: '/escrows/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEscrowsIdRoute = AppEscrowsIdRouteImport.update({
  id: '/escrows/$id',
  path: '/escrows/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agent': typeof AppAgentRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/new-deal': typeof AppNewDealRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/escrows/$id': typeof AppEscrowsIdRoute
  '/app/suppliers/$id': typeof AppSuppliersIdRoute
  '/app/escrows/': typeof AppEscrowsIndexRoute
  '/app/suppliers/': typeof AppSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agent': typeof AppAgentRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/new-deal': typeof AppNewDealRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/escrows/$id': typeof AppEscrowsIdRoute
  '/app/suppliers/$id': typeof AppSuppliersIdRoute
  '/app/escrows': typeof AppEscrowsIndexRoute
  '/app/suppliers': typeof AppSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agent': typeof AppAgentRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/new-deal': typeof AppNewDealRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/escrows/$id': typeof AppEscrowsIdRoute
  '/app/suppliers/$id': typeof AppSuppliersIdRoute
  '/app/escrows/': typeof AppEscrowsIndexRoute
  '/app/suppliers/': typeof AppSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/api/chat'
    | '/app/agent'
    | '/app/analytics'
    | '/app/documents'
    | '/app/new-deal'
    | '/app/risk'
    | '/app/settings'
    | '/app/'
    | '/app/escrows/$id'
    | '/app/suppliers/$id'
    | '/app/escrows/'
    | '/app/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/api/chat'
    | '/app/agent'
    | '/app/analytics'
    | '/app/documents'
    | '/app/new-deal'
    | '/app/risk'
    | '/app/settings'
    | '/app'
    | '/app/escrows/$id'
    | '/app/suppliers/$id'
    | '/app/escrows'
    | '/app/suppliers'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/api/chat'
    | '/app/agent'
    | '/app/analytics'
    | '/app/documents'
    | '/app/new-deal'
    | '/app/risk'
    | '/app/settings'
    | '/app/'
    | '/app/escrows/$id'
    | '/app/suppliers/$id'
    | '/app/escrows/'
    | '/app/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-deal': {
      id: '/app/new-deal'
      path: '/new-deal'
      fullPath: '/app/new-deal'
      preLoaderRoute: typeof AppNewDealRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers/': {
      id: '/app/suppliers/'
      path: '/suppliers'
      fullPath: '/app/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escrows/': {
      id: '/app/escrows/'
      path: '/escrows'
      fullPath: '/app/escrows/'
      preLoaderRoute: typeof AppEscrowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers/$id': {
      id: '/app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/app/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escrows/$id': {
      id: '/app/escrows/$id'
      path: '/escrows/$id'
      fullPath: '/app/escrows/$id'
      preLoaderRoute: typeof AppEscrowsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNewDealRoute: typeof AppNewDealRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEscrowsIdRoute: typeof AppEscrowsIdRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppEscrowsIndexRoute: typeof AppEscrowsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppNewDealRoute: AppNewDealRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEscrowsIdRoute: AppEscrowsIdRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppEscrowsIndexRoute: AppEscrowsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
